### ISSUE TITLE
reload unexpectedly succeeds

### ISSUE THREAD

**Issue by richdrich** [ActsAsParanoid/acts_as_paranoid#101]
```
o = Paranoic.first
o.destroy
o.reload
```

With real deletes, raises `RecordNotFound`. With acts_as_paranoid, succeeds and reloads the deleted record.

Not important, I know...

**Comment by mvz** [comment]
@richdrich given what ActsAsParanoid aims to accomplish, what behavior would you expect?

**Comment by richdrich** [comment]
I think it should raise RecordNotFound. Just on a basis of behaving exactly like a hard delete.

**Comment by mvz** [comment]
Ok, so what about:

```
o = Paranoic.first
o.destroy
o = Paranoic.with_deleted.first
o.reload
```

**Comment by mvz** [comment]
I'm afraid I don't see any particular use case for raising `RecordNotFound`. The intention of ActsAsParanoid is precisely not to behave exactly like a hard delete.

If you can supply a use case for this I'm willing to reconsider, but for now I'll close this ticket.
