### ISSUE TITLE
Gem release for rails 5.1

### ISSUE THREAD

**Issue by nbarthelemy** [ActsAsParanoid/acts_as_paranoid#104]
Hello -

I am wondering when we can anticipate a gem release for > rails 5.0. We are pulling master into our project, but we need a formally published gem to add to our gemspec. Any help would be greatly appreciated.

Thanks

**Comment by goravbhootra** [comment]
Duplicate of https://github.com/ActsAsParanoid/acts_as_paranoid/issues/88
