### ISSUE TITLE
Do not override default scope

### ISSUE THREAD

**Issue by kotovalexarian** [ActsAsParanoid/acts_as_paranoid#111]
Overriding default scope with filtering condition is considered to be a bad practice. I ran into problems several times because of this. Instead you should create named scope to be used to exclude deleted records.

**Comment by Noejoaquin** [comment]
@kotovalexarian Would love to hear more about your experience with this. Maybe some examples? Do you think the `scopes` section of the documentation could use a revamp with respect to what you raise here? Maybe instead of the `scopes` section, the `caveats` section?

**Comment by mvz** [comment]
Closing due to lack of feedback from the original poster.
