### ISSUE TITLE
getting ready for rails 6

### ISSUE THREAD

**Issue by phoet** [ActsAsParanoid/acts_as_paranoid#115]
i'm currently preparing for migration to rails-6 beta1.

the test-suite is running https://github.com/penseo/acts_as_paranoid/pull/1

since i do not have any idea what i'm doing here, please gimme some help.

cheers!

**Comment by danielricecodes** [comment]
Got my hopes up but this fork has nothing to do with Rails 6....

**Comment by phoet** [comment]
Latest should work with rails 6!

**Comment by vakrolme** [comment]
For me it works with `rails 6.0.0.rc2`. However when I change rails version to `6.0.0`, I get the following error on bundle update/install:
```
Bundler could not find compatible versions for gem "activerecord":
  In snapshot (Gemfile.lock):
    activerecord (= 6.0.0)

  In Gemfile:
    acts_as_paranoid (~> 0.6.0) was resolved to 0.6.0, which depends on
      activerecord (>= 4.2, < 6.0)

    rails (~> 6.0) was resolved to 6.0.0, which depends on
      activerecord (= 6.0.0)
```
Is it just me?

**Comment by mvz** [comment]
@vakrolme the latest gem release (0.6.0) does not support Rails 6 (I think @phoet means latest master).

However, I'm preparing release 0.6.1 *right now*, which will include Rails 6 support :rocket:.

**Comment by mvz** [comment]
... and released it is.
