### ISSUE TITLE
Idea for improved database performance

### ISSUE THREAD

**Issue by peterwake** [ActsAsParanoid/acts_as_paranoid#121]
With a database index on deleted_at (as a timestamp) we don't get great leverage of the indexing power of the database. So I was thinking it might be good to have two (or three) database columns

- `deleted_at` as a timestamp
- `deleted_at_date` as a date (optional)
- `deleted` as a boolean

Then adding indexes on `deleted` and `deleted_at_date` (optional).

Any thoughts / suggestions appreciated

**Comment by dsounded** [comment]
Not sure if indexing of boolean field is much efficient

**Comment by mvz** [comment]
This probably depends a lot on the specific database. From some shallow research, it seems that
- PostgreSQL allows indexing on just the date part of the timestamp
- MySQL can use a datetime index just fine

So, I don't see the need for this added complexity. If there are issues with a specific query, feel free to create a new ticket.
