### ISSUE TITLE
Rails 6. Can't modify frozen hash

### ISSUE THREAD

**Issue by vitalinfo** [ActsAsParanoid/acts_as_paranoid#129]
Look's like `destroy_fully!` doesn't work in Rails 6.
It raises `Can't modify frozen hash`

**Comment by yevhene** [comment]
@vitalinfo Stuck with this issue with Rails 5.0.7.2 (during upgrade from Rails 4.2). Did you find the solution?

**Comment by vitalinfo** [comment]
@yevhene what the issue? could you please specify?

**Comment by yevhene** [comment]
@vitalinfo `destroy_fully!` raise `Can't modify frozen hash`

**Comment by vitalinfo** [comment]
@yevhene hm... I didn't experience such problem on lower Rails versions

**Comment by yevhene** [comment]
@vitalinfo Did you find any hints on what is the cause? I think it is similar anyway.

**Comment by vitalinfo** [comment]
@yevhene I've added a few workarounds that works for me 
https://github.com/vitalinfo/acts_as_paranoid with Rails 6

**Comment by frostblooded** [comment]
I am also experiencing this issue on Rails 5.2.3 with acts_as_paranoid 0.6.2. @vitalinfo's fork works well for me. Although I have found that calling `#destroy` on a soft-deleted model sometimes also generates this error. It is trying to touch an already destroyed object, I suppose.

**Comment by yevhene** [comment]
@frostblooded Yes, it is related to touching

**Comment by mvz** [comment]
@vitalinfo Does this problem still occur with version 0.6.3?

**Comment by vitalinfo** [comment]
@mvz nope, version 0.6.3 doesn't work for me as well.

**Comment by mvz** [comment]
@vitalinfo can you provide a backtrace or some other context? I'm having a hard time reproducing this.

**Comment by vitalinfo** [comment]
@mvz I did deep dive into the problem today and looks like problem in my code (overcomplicated optimization), 0.6.3 is working for me now and you can close this issue.
Thanks

**Comment by mvz** [comment]
Thanks for looking into this, @vitalinfo!
