### ISSUE TITLE
Only run `recover` when model is already deleted

### ISSUE THREAD

**Issue by marycodes2** [ActsAsParanoid/acts_as_paranoid#132]
We are currently able to call the `recover` method on a model instance that has not been deleted. We would expect that `recover` would be a no-op on records that have not been deleted. Instead, we noticed that all callbacks and lifecycle methods are invoked when `recover` is called on a record with `deleted_at: nil`.

We would be happy to submit a PR with this change if you'd like!

**Comment by marycodes2** [comment]
Here is a PR that solves this issue:

https://github.com/ActsAsParanoid/acts_as_paranoid/pull/133

**Comment by mvz** [comment]
#133 was merged, thanks again!
