### ISSUE TITLE
Rollback is not called if destroy fails

### ISSUE THREAD

**Issue by Able1991** [ActsAsParanoid/acts_as_paranoid#140]
Hi.
I call throw(:abort) in before_destroy callback and wait rollback for restore has_many :dependent => :destroy records, but rollback does not occur

https://gist.github.com/Able1991/8291b9ba95fd5f1d1adb6d6c751932a1

![image](https://user-images.githubusercontent.com/3898046/69525378-0bb39780-0f79-11ea-8396-fcd78a66a244.png)
but I expect a rollback)

**Comment by dongapplyboard** [comment]
Hey have you found any solution to this as of yet? I'm getting the same error, it seems that the `throw :abort` doesn't fire and the destroy goes through regardless of the `before_destroy` validation

**Comment by Able1991** [comment]
this is another gem ;)
