### ISSUE TITLE
destroy_all doesn't work properly

### ISSUE THREAD

**Issue by vitalinfo** [ActsAsParanoid/acts_as_paranoid#155]
Looks like `destroy_all` doesn't work for has_many association which has a scope `with_deleted`, like

```
class Company < ApplicationRecord
  acts_as_paranoid 
  has_many :users, -> { User.with_deleted }
end

class User < ApplicationRecord
  acts_as_paranoid 
  belongs_to :company
end

Company.first.users.destroy_all # doesn't work
```

**Comment by mvz** [comment]
Hi @vitalinfo what do you mean by 'doesn't work'? What happens instead or what error messages do you get?

**Comment by vitalinfo** [comment]
@mvz nothing, any exceptions, but objects aren't destroyed in the collection

**Comment by mvz** [comment]
What I expect to happen is that all users will become deleted, but they can still be found from the `users` collection since that collection always also includes the deleted users.

@vitalinfo can you confirm whether the user objects have themselves been destroyed?

**Comment by mvz** [comment]
Closing this since no more info was received.
