### ISSUE TITLE
version not available

### ISSUE THREAD

**Issue by Faisal-nfl** [ActsAsParanoid/acts_as_paranoid#162]
You guys ask to use 
`gem 'acts_as_paranoid', '~> 0.7.0'`

while [rubygems](https://rubygems.org/gems/acts_as_paranoid) says that latest available version is

> 0.6.3 - January 25, 2020

whats happening here?

**Comment by mvz** [comment]
> whats happening here?

The README in the repo has been adjusted for the next version to be released. You can use 0.6.3 for now.
