### ISSUE TITLE
validates_uniqueness_of_without_deleted undefined in Rails 4.2

### ISSUE THREAD

**Issue by suan** [ActsAsParanoid/acts_as_paranoid#20]
More of an FYI I suppose since 4.2 is not official yet, but the above method is undefined both on master and on 0.5.0.beta1 when used as instructed in the README

**Comment by allaire** [comment]
Any update on this @zzak ?

**Comment by zzak** [comment]
@allaire there is a patch, maybe you can point your Gemfile to @mvz's `fix-build` branch?

https://github.com/mvz/acts_as_paranoid/tree/fix-build

If you try it please report any issues to #26, thank you!

**Comment by vaughanj10** [comment]
+1

**Comment by zzak** [comment]
This should be fixed in the last release, please check it. <3

**Comment by zzak** [comment]
Please try 0.5.0, this should be fixed now
