### ISSUE TITLE
Option touch: true does not work together with counter_cache: true when destroying.

### ISSUE THREAD

**Issue by pilgunboris** [ActsAsParanoid/acts_as_paranoid#206]
Touching doesn't work on destroy in `belongs_to` association definition with `touch: true` and `counter_cache: true` used together:
```Ruby
belongs_to :association_name, optional: true, touch: true, counter_cache: true, with_deleted: true
```
It still works after creating but not after destroying.

To make sure there is an issue in acts_as_paranoid I've tried to disable  it for this model and this scenario works well without it.

**Comment by pilgunboris** [comment]
Looks like there exists a PR that shows the problem: https://github.com/ActsAsParanoid/acts_as_paranoid/pull/174

**Comment by mvz** [comment]
The underlying issue seems to be that Rails' touch and counter cache callbacks are not independent, and ActsAsParanoid only recreates the counter cache behavior with its own custom code, skipping the touch functionality.

**Comment by pilgunboris** [comment]
@mvz thanks for fixing it 👍
