### ISSUE TITLE
Using with public_activity gem

### ISSUE THREAD

**Issue by noctivityinc** [ActsAsParanoid/acts_as_paranoid#21]
I am using ```https://github.com/pokonski/public_activity``` on a number of models that I am protecting with acts_as_paranoid.  Right now when an associated record that is tracked is destroyed, it cannot be viewed in rendered activities because the polymorphic association checks for records that are not deleted, which is standard behavior with the gem.  I would like, however, to be able to override this behavior so that deleted records are included in the association.  

I tried something like this:

    class IdeaHistory < ActiveRecord::Base
        include PublicActivity::Renderable

        self.table_name = PublicActivity.config.table_name

        acts_as_paranoid

        # Define polymorphic association to the parent
        belongs_to :trackable, :polymorphic => true
        # Define ownership to a resource responsible for this activity
        belongs_to :owner, :polymorphic => true
        # Define ownership to a resource targeted by this activity
        belongs_to :recipient, :polymorphic => true, with_deleted: true
        belongs_to :recipient_including_deleted, :class_name => "Idea", :foreign_key => 'recipient_id', :with_deleted => true
        # Serialize parameters Hash
        serialize :parameters, Hash

        if ::ActiveRecord::VERSION::MAJOR < 4 || defined?(ProtectedAttributes)
          attr_accessible :key, :owner, :parameters, :recipient, :trackable
        end
    end

where I hard coded the recipient to be one of my models but it did not work.  Do you have any idea how I can get public_activity and acts_as_paranoid to work well together?

**Comment by zzak** [comment]
So it seems there is a workaround for this issue ( chaps-io/public_activity#186 ), and I'm not sure there's anything we can do about it here.. so close.

**Comment by Merovex** [comment]
The issue you reference @zzak is not a working work-around. Closed prematurely.
