### ISSUE TITLE
Emulate difference between `destroy` and `destroy!` in default ActiveRecord

### ISSUE THREAD

**Issue by mvz** [ActsAsParanoid/acts_as_paranoid#221]
In ActiveRecord, `destroy!` raises `ActiveRecord::RecordNotDestroyed` if `before_destroy` aborts, whereas `destroy` just returns `false`. ActsAsParanoid should do the same.

**Comment by leomayleomay** [comment]
@mvz thank you for bringing this up, any plan on this? cheers

**Comment by mvz** [comment]
No, there's no work in progress on this. Pull requests welcome, of course.

**Comment by leomayleomay** [comment]
@mvz PR filed https://github.com/ActsAsParanoid/acts_as_paranoid/pull/240, please help to review, cheers

**Comment by mvz** [comment]
Fixed in #240
