### ISSUE TITLE
delete_all with associations

### ISSUE THREAD

**Issue by iffyuva** [ActsAsParanoid/acts_as_paranoid#27]
i have upgraded from rails 4.0.2 to 4.1.8, and i'm facing this issue with associations

``` ruby
class Reservation < AR::Base
  has_many :bookings
end

class Booking < AR::Base
  acts_as_paranoid

  belongs_to :reservation
end

r = Reservation.create(params)
b = Booking.create(reservation: r)

# does not work. does not set deleted_at to some Time.
# sql that im seeing is:
#  UPDATE "bookings" SET "reservation_id" = NULL WHERE
#    ("bookings"."deleted_at" IS NULL) AND 
#    "bookings"."reservation_id" = $1  [["reservation_id", 1]]
r.bookings.delete_all

# works, sets deleted_at to proper value.
# sql that im seeing is:
# UPDATE "bookings" SET "deleted_at" = '2015-01-02 13:07:06.374754' WHERE
#    ("bookings"."deleted_at" IS NULL) AND "bookings"."id" IN (1)
Booking.where(id: r.bookings.map(&:id)).delete_all
```

is this a known issue?

**Comment by zzak** [comment]
@iffyuva Does this issue still affect you on the latest version?

**Comment by iffyuva** [comment]
@zzak you mean on rails 4.2.4 ?

**Comment by zzak** [comment]
@iffyuva The latest version of `acts_as_paranoid`: https://rubygems.org/gems/acts_as_paranoid/versions/0.5.0.beta2

**Comment by zzak** [comment]
In fact, this seems like the current behavior from what I can see by the tests:
https://github.com/ActsAsParanoid/acts_as_paranoid/blob/master/test/test_relations.rb#L112

For example:
```ruby
@paranoid_forest_2.paranoid_trees.order(:id).delete_all!
```
and
```ruby
@paranoid_forest_1.paranoid_trees.order(:id).destroy(paranoid_tree.id)
```

For whatever reason, we must do this.

You could simplify your code to just `r.bookings.order(:id).delete_all`, I believe.

So perhaps this could be improved in the documentation.

**Comment by mvz** [comment]
As far as I can tell this problem no longer occurs.
