### ISSUE TITLE
Wrong SQL generated for with_deleted

### ISSUE THREAD

**Issue by jodosha** [ActsAsParanoid/acts_as_paranoid#29]
Hello, at Litmus we have two classes `Account` and `User` in a "1 to n" relationship.
We use `acts_as_paranoid` in both the classes.

We're upgrading to Rails 4.2, and we noticed this wrong generated SQL.

```ruby
[2] pry(main)> account.users.with_deleted.to_sql
=> "SELECT `users`.* FROM `users`"
```

The expected query is:

```ruby
[2] pry(main)> account.users.with_deleted.to_sql
=> "SELECT `users`.* FROM `users` WHERE `users`.`account_id` = 1"
```

This is already solved by https://github.com/ActsAsParanoid/acts_as_paranoid/pull/26 Can you please merge it? :blue_heart: :green_heart: :heart: :yellow_heart: :heart: Thank you!

**Comment by zzak** [comment]
@jodosha Was this fixed? <3

**Comment by jodosha** [comment]
@zzak I can't verify anymore, cause not longer working on that code base :dancer:

**Comment by zzak** [comment]
Since #26 was merged, we can close this. <3
