### ISSUE TITLE
Documentation says .recover to restore deleted model but you need to do .restore

### ISSUE THREAD

**Issue by imfuna** [ActsAsParanoid/acts_as_paranoid#32]
Checked tests and recovery is now done with .restore.

**Comment by Jerph** [comment]
You may be thinking of the [Paranoia gem](https://github.com/radar/paranoia), which has a similar API but is different in this case.

**Comment by zzak** [comment]
I'm not sure, but we don't have `restore` in this project.

It's possible you are thinking of a different gem, please confirm and re-open if you have any issues. <3
