### ISSUE TITLE
Rails 8 Issue?

### ISSUE THREAD

**Issue by fmorton** [ActsAsParanoid/acts_as_paranoid#356]
Converting from rails 7.2.2 to 8.0.0 and getting this:

/Users/fmorton/.rbenv/versions/3.2.5/lib/ruby/gems/3.2.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:42:in `alias_method': undefined method `validate_find_options' for class `#<Class:ActiveRecord::Base>' (NameError)

            alias_method :validate_find_options_without_deleted, :validate_find_options
            ^^^^^^^^^^^^
	from /Users/fmorton/.rbenv/versions/3.2.5/lib/ruby/gems/3.2.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:42:in `singleton class'
	from /Users/fmorton/.rbenv/versions/3.2.5/lib/ruby/gems/3.2.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:41:in `included'
	from /Users/fmorton/.rbenv/versions/3.2.5/lib/ruby/gems/3.2.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:166:in `include'
	from /Users/fmorton/.rbenv/versions/3.2.5/lib/ruby/gems/3.2.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:166:in `<main>'
	from /Users/fmorton/.rbenv/versions/3.2.5/lib/ruby/gems/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'

**Comment by mvz** [comment]
Hi @fmorton this is the same problem is #342. Please add "~> 0.10.2" to your `acts_as_paranoid` dependency to avoid Bundler picking an ancient version. Rails 8 support is coming soon!

**Comment by fmorton** [comment]
I will be happy to try it out when you are ready. Here is what I get now with a "bundle update":

Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Could not find compatible versions

Because acts_as_paranoid >= 0.10.2 depends on activesupport >= 6.1, < 8
  and rails >= 8.0.0 depends on activesupport = 8.0.0,
  acts_as_paranoid >= 0.10.2 is incompatible with rails >= 8.0.0.
So, because Gemfile depends on rails ~> 8.0.0
  and Gemfile depends on acts_as_paranoid ~> 0.10.2,
  version solving has failed.

Thanks for your work on this. It is a great gem.

**Comment by cancelei** [comment]
I also am getting the same message, I'm considering changing to other gem.

**Comment by mvz** [comment]
@cancelei as I mentioned to @fmorton, please try pinning acts_as_paranoid's version to `"~> 0.10.2"`, and use Rails 7. Without pinning the version, Bundler will pick a very old version if you try to use acts_as_paranoid with Rails 8.

You're welcome to use another gem if that suits your needs better.

**Comment by mvz** [comment]
Version 0.10.3 supporting Rails 8.0 has now been released.

**Comment by fmorton** [comment]
Thanks for adding the Rails 8 support and appreciate all your work on this gem.
