### ISSUE TITLE
Unable to upgrade my project to Rails 8 as their is a dependency issue of acts_as_paranoid with activesupport 8.0

### ISSUE THREAD

**Issue by rajneeshsharma9** [ActsAsParanoid/acts_as_paranoid#358]
Because acts_as_paranoid >= 0.9.0, < 0.10.2 depends on activesupport >= 6.1, < 7.2
  and acts_as_paranoid >= 0.10.2 depends on activesupport >= 6.1, < 8,
  acts_as_paranoid >= 0.9.0 requires activesupport >= 6.1, < 8.
And because rails >= 8.0.0 depends on activesupport = 8.0.0,
  acts_as_paranoid >= 0.9.0 is incompatible with rails >= 8.0.0.
So, because Gemfile depends on rails ~> 8.0.0
  and Gemfile depends on acts_as_paranoid ~> 0.10.0,
  version solving has failed.

**Comment by mvz** [comment]
Version 0.10.3 supporting Rails 8.0 has now been released.

**Comment by rajneeshsharma9** [comment]
@mvz  thanks a ton for doing this so quickly.
