### ISSUE TITLE
`decrement_counters` stop working in rails 4

### ISSUE THREAD

**Issue by pauldruziak** [ActsAsParanoid/acts_as_paranoid#39]
I upgrading our app to rails 4 and found that now when user remove some record it's not decrement cached counters. Researching how to fix it. Maybe somebody has some idea.

**Comment by paveldruzyak** [comment]
Actually `ActiveRecord::CounterCache.destroy_row` should be called, but this not happened.

**Comment by jthibeaux** [comment]
I just ran across this and was going in circles to trying to figure out if I was doing anything wrong or if this should be expected to work.  Hope the PR gets merged.

**Comment by zzak** [comment]
This should be fixed by #40 

Thank you!

**Comment by zzak** [comment]
Unfortunately the patch in #40 didn't work with Rails 5, so it was reverted.

**Comment by davidguthu** [comment]
Whats the status on this? Anyone working on it?

**Comment by filipebarros** [comment]
@zzak wasn't this fixed by https://github.com/ActsAsParanoid/acts_as_paranoid/pull/119 ?
