### ISSUE TITLE
validates_uniqueness_of_without_deleted :column fails for serialized columns

### ISSUE THREAD

**Issue by jamilbk** [ActsAsParanoid/acts_as_paranoid#43]
Rails 4.2.3
Ruby 2.3.0p0
Linux x86-64

``` ruby
class Foo < ActiveRecord::Base
  acts_as_paranoid
  validates_as_paranoid
  serialize :colors, Array

  validates_uniqueness_of_without_deleted :colors
end
```

This raises the exception `ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be an Array, but was a String.` when calling `@foo.update_attributes` with a new `colors` array.

Are serialized fields supported by `validates_uniqueness_of_without_deleted`?

**Comment by zzak** [comment]
I haven't heard of anyone running into this issue before, but there might also be no tests for this behavior.

**Comment by patientdev** [comment]
This is related to the changes in PR #83. `validates_uniqueness_of_without_deleted` is using the `type_cast_for_schema` method to cast the value, which simply calls `.inspect` on an array, returning a string.
