### ISSUE TITLE
wrong sql generated when used with database_cleaner and multiple database adapters

### ISSUE THREAD

**Issue by fmnoise** [ActsAsParanoid/acts_as_paranoid#50]
We found and issue, when `acts_as_paranoid` is used with `database_cleaner` gem and multiple database adapters like `mysql` and `postgresql`. We had the following errors
> Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '."deleted_at" IS NULL) LIMIT 1' at line 1: SELECT  `users`.* FROM `users` WHERE `users`.`id` = 42 AND ("users"."deleted_at" IS NULL) LIMIT 1

Pushed #49 for fixing it

**Comment by zzak** [comment]
I've merged #49 so this issue can be closed.
