### ISSUE TITLE
destroy! and destroy_fully! not documented

### ISSUE THREAD

**Issue by jessegoodnoe** [ActsAsParanoid/acts_as_paranoid#51]
The documentation is incorrect for Real Deletion. 

destroy! no longer does the actual deletion. It needs to be called twice, just like destroy.  If you want something destroyed permanently you need to call destroy_fully!

Per the commit comment:
```
Soft destroy dependents
The dependent destroy callback mechanism in Rails calls destroy! instead
of destroy for has_many associations. With the existing implementation
of acts_as_paranoid, this would unintentionally cause dependent objects
to be hard-destroyed. This change makes destroy and destroy! identical,
and adds a separate destroy_fully! method for full destroy.
```

**Comment by zzak** [comment]
@jessegoodnoe Can you point me to the commit?

Also, brownie points for a PR to fix the documentation <3

**Comment by zzak** [comment]
Nevermind, I found the commit: e8f7fbb1004c010e87cd11e648a914621c367043
