### ISSUE TITLE
undefined method `validate_find_options' for class `

### ISSUE THREAD

**Issue by alikhan-io** [ActsAsParanoid/acts_as_paranoid#52]
With the latest version (5.0.rc1) I seem ot be getting an error generating a rails migration for acts_as_paranoid for a model that already exists. 

rails generate migration MakeEventParanoid
/home/dominusk/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'acts_as_paranoid'.
Gem Load Error is: undefined method `validate_find_options' for class `#<Class:ActiveRecord::Base>'

Note I am running Rails 5.0 along with Devise, Pundit and Rolify. It eventually traces back to my application.rb config line 17 which is 

Bundler.require. Below is a snapshot of the application.rb code from line 1-17

```
`require_relative 'boot'

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
# require "sprockets/railtie"
require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)`
```

I have confirmed the migration creation will work fine if I comment out the paranoid gem. So definitely something related to acts_as_paranoid

**Comment by zzak** [comment]
@alikhan-io Thanks for trying the release candidate, and your report!

I will try to reproduce this error and see if I can fix it.

**Comment by alikhan-io** [comment]
Derp. Closing this as I realized I was in fact -NOT- using the RC. Works fine! Positive vote for the RC! List of gems I am using it with just for additional positive compatibility knowledge.

gem 'devise', '~> 4.2'
gem 'pundit', '~> 1.1'
gem 'rolify', '~> 5.1'
gem 'paper_trail', '~> 5.2'
gem 'pg', '~> 0.18.4'
gem 'acts_as_paranoid', '~> 0.5.0.rc1'
