### ISSUE TITLE
'Recovering dependent associations' doesn't work

### ISSUE THREAD

**Issue by tomajask** [ActsAsParanoid/acts_as_paranoid#57]
Hi!

I've got a problem with recovering dependent associations. Here is my case.

I have a `SuperUser` class inherited from `User` class and this `SuperUser` `has_one` profile (`SuperUsersProfile`):

`SuperUser`:

``` ruby
class SuperUser < User
  acts_as_paranoid
  has_one :profile, class_name: 'SuperUsersProfile', inverse_of: :super_user, dependent: :destroy
  ...
end
```

`SuperUsersProfile`:

``` ruby
class SuperUsersProfile < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :super_user, inverse_of: :profile
  ...
end

```

When I destroy particular SuperUser, it works perfectly fine. SuperUser is destroyed with its profile. Unfortunately it doesn't work for recovering. When I try to recover SuperUser it recovers only SuperUser and SuperUsersProfile is not recovered. I would appreciate if you could check it.

It's not a big deal for me. I wrote a separate module to handle that so it works. But maybe someone would come across this case also in the future.

**Comment by baswenneker** [comment]
How about sharing your solution?

**Comment by tomajask** [comment]
Sorry for the delay:
```ruby
module ProfileRecoverable
  extend ActiveSupport::Concern
  included do
    after_recover :restore_profile

    private

    def dependent_class
      "#{type.pluralize}Profile".constantize
    end

    def association_scope
      dependent_class.only_deleted.where("#{type.downcase}_id" => id).order(created_at: :desc)
    end

    def restore_profile
      association_scope.first.recover
    end
  end
end

```

**Comment by KidA001** [comment]
I'd like to bump this thread. `recover` is not restoring `has_one` associations, only `has_many`. Any idea why this isn't built it?

**Comment by mvz** [comment]
You may have to reload the parent model to make the associated model appear again.

**Comment by mvz** [comment]
Reloading should no longer be necessary.
