### ISSUE TITLE
disable panaroid with some models

### ISSUE THREAD

**Issue by BrahimDahmani** [ActsAsParanoid/acts_as_paranoid#58]
I'm using Rails 5, i want the majority of models acts_as_panaroid so i did this

``` Ruby
class ApplicationRecord < ActiveRecord::Base
  acts_as_paranoid
  self.abstract_class = true
end
```

Now all my models are acting as panaroid, but i want to exclude some of them

Exemple:

``` Ruby
class ClassA < ApplicationRecord
end
```

``` Ruby
class ClassB < ApplicationRecord
end
```

``` Ruby
class ClassC < ApplicationRecord
end
```

``` Ruby
class ClassD < ApplicationRecord
end
```

I want `ClassC` not to acts_as_panaroid

is there any solution for that??

**Comment by zzak** [comment]
How about to try:

```ruby
class ClassC < ActiveRecord::Base
end
```

**Comment by mvz** [comment]
Closing this since the question has been answered.
