### ISSUE TITLE
ArgumentError: Unknown key: :with_deleted

### ISSUE THREAD

**Issue by alexandre025** [ActsAsParanoid/acts_as_paranoid#59]
Hi there, i found an issue with rails 5 

> ArgumentError: Unknown key: :with_deleted. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :foreign_type, :dependent, :primary_key, :inverse_of, :required, :polymorphic, :touch, :counter_cache, :optional

For this classical model : 

> class Payment < ApplicationRecord
> acts_as_paranoid
> belongs_to :payment_method, with_deleted: true
> end

Anyone has the same problem ? 

Thanks !

**Comment by emiddleton** [comment]
I am having this issue.  Did you find a solution.

**Comment by puntodamar2** [comment]
use `associated_table, -> { with_deleted }`

**Comment by mvz** [comment]
This should actually just work as an option instead of a lambda. @puntodamar2 do you see this problem with the current release of acts as paranoid?

**Comment by allencch** [comment]
In case someone has same issue when using `with_deleted: true`, the (alternative) solution is

```ruby
belongs_to :parent_including_deleted, -> { with_deleted }, class_name: "Parent", foreign_key: 'parent_id'
```

**Comment by mvz** [comment]
@allencch I'm going to ask you the same question as I asked @puntodamar2: Do you see this problem with `with_deleted: true` in the current release of acts as paranoid?

**Comment by allencch** [comment]
@mvz , I just found that I was confused with the gem `acts_as_paranoid` and `paranoia`, as Google search leads to this thread.

The solution above supposes to work on `paranoia` gem instead of `acts_as_paranoid`. Sorry for the confusion.

**Comment by mvz** [comment]
No problem, thanks for getting back to me @allencch.
