### ISSUE TITLE
Support for recover!

### ISSUE THREAD

**Issue by avinoth** [ActsAsParanoid/acts_as_paranoid#65]
currently on `recover` method, it fails silently returning `false` when the validations for the model fails, similar to `create` or `update`. It would be nice to have a support for `recover!` method which raises an exception on validation fails.

I'm currently doing this by overriding `recover` in my model but it would be nice to have a support for this. I can create a PR for this if okay.

**Comment by zzak** [comment]
Patches welcome :)

**Comment by mvz** [comment]
This was fixed in #75.
