### ISSUE TITLE
Have option to recover dependent associations after parent recover

### ISSUE THREAD

**Issue by avinoth** [ActsAsParanoid/acts_as_paranoid#66]
Currently the associations are recovered before the parent association is recovered. In the association though, there's no way to know if the recovery is propagating from the parent or was directly invoked.

**Comment by mvz** [comment]
@avinoth what were you trying to achieve that didn't work because of this?

**Comment by mvz** [comment]
This may be related to #216.

**Comment by mvz** [comment]
Closing this since #216 was fixed and no info was received on this issue.
