### ISSUE TITLE
Why the project is failing?

### ISSUE THREAD

**Issue by noise2** [ActsAsParanoid/acts_as_paranoid#73]
The project is failing and I have updated my gems, we are depending on this gem at the production level, can I ask what is the problem?

**Comment by zzak** [comment]
@noise2 Can you explain? How is it failing for you?

**Comment by noise2** [comment]
@zzak we haven't had anything to notice the failing, but the [Travis-CI](https://travis-ci.org/ActsAsParanoid/acts_as_paranoid/)'s [![Build Status](https://travis-ci.org/ActsAsParanoid/acts_as_paranoid.svg?branch=master)](https://travis-ci.org/ActsAsParanoid/acts_as_paranoid) red flag worries us!

**Comment by zzak** [comment]
Ahh, yeah that is a known issue. See #71
