### ISSUE TITLE
alias_method_chain is deprecated. Please, use Module#prepend instead

### ISSUE THREAD

**Issue by kuldeepdaffodil** [ActsAsParanoid/acts_as_paranoid#81]
Hi

Please check below WARNING when I am using command line interface . 

DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from singleton class at /home/daffolap-244/.rvm/gems/ruby-2.3.0@diary/gems/acts_as_paranoid-0.5.0/lib/acts_as_paranoid/associations.rb:6)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block in included at /home/daffolap-244/.rvm/gems/ruby-2.3.0@diary/gems/acts_as_paranoid-0.5.0/lib/acts_as_paranoid/preloader_association.rb:11)

**Comment by jacob-on-github** [comment]
See #78

**Comment by mvz** [comment]
Fixed in 0.6.0!
