### ISSUE TITLE
Throw error when adding scope in Association

### ISSUE THREAD

**Issue by MuhammadRazaAslam** [ActsAsParanoid/acts_as_paranoid#90]
Hey,
My rails version is rails-3.2.22.5 and ack_as_paranoid version is acts_as_paranoid-0.4.5. When i try to add scope in belong_to association then it throws exception during getting any record from db. Let me know why it's happening. Here is my code

**class Touch < ActiveRecord::Base
  acts_as_paranoid
has_many :touch_transactions, class_name: "ActivityTransactions", :foreign_key => 'touch_id'
end**

**class ActivityTransactions < ActiveRecord::Base
  belongs_to :touch, -> {Touch.all}
end**

If i removed scope then it will work fine.

**Comment by mvz** [comment]
I can't reproduce this.

@MuhammadRazaAslam do you still experience this issue? If so, can you please provide a clear way to reproduce this error, as well as details on what exception is thrown?
