### ISSUE TITLE
How to recover children items after recoverd parent item

### ISSUE THREAD

**Issue by hoan-nguyen-dinosys** [ActsAsParanoid/acts_as_paranoid#91]
I have groups model and it has parent/children associations. When I destroy parent item, all children items destroy . But, I recover parent item, children items not recover. I tried options of recover in document.

**Comment by chiperific** [comment]
What happens if you do this: 
`Parent.restore(@parent.id, :recursive => true)`

**Comment by jantequera** [comment]
This was happening on a project to me as well.

`Parent.rstore` does not exist (or so it seems) in actas_as_paranoid, Parent.recover does, but does not do the trick.

I've decided to migrate to the `paranoia` gem, which is almost seamless (couple of method renaming).

Best movement though would be moving to the `discard` gem, sinca paranoia is in maintenance mode, but it takes more work to do the migration, so I'll do it in a next iteration.

**Comment by mvz** [comment]
There was an issue with recovering children that had (automatic) validation on presence of the parent. This has been fixed in #227.
